routes/web.php
<?php

/* echo "<pre>";
for($i=40;$i<=400;$i++){
		echo "(".(18800+$i).",'DELUXE','80',".$i."),\n";
}
for($i=40;$i<=400;$i++){
		//echo "(".(18400+$i).",'GOFRE','80',".$i."),\n";
}
die; */

Route::get("test",function(){
	return view("print.test");
});
Route::get("login","Auth\LoginController@showLoginForm")->name("login");
Route::post("login","Auth\LoginController@login");
Route::post("logout","Auth\LoginController@logout")->name("logout");

Route::group(['guard' => 'web'], function () {
	Route::get('/', 'TumController@index')->name("home");
	Route::get('/onay', 'OnayController@index');
	Route::get('/hazirlik', 'HazirlikController@index');
	Route::get('/uretimde', 'UretimdeController@index'); //1
	Route::get('/transfer', 'TransferdeController@index');
	Route::get('/transfer/panel', 'TransferdeController@panel');
	Route::get('/uretilen', 'UretilenController@index');
	Route::get('/cikislar', 'CikislarController@index');
	Route::get('/cikislar/panel', 'CikislarController@panel');
	Route::get('/dagitimda', 'DagitimdaController@index');
	Route::get('/tum', 'TumController@index');
	Route::post('/tum/excel', 'TumController@excel');
	Route::get('/fatura', 'FaturaController@index');
	Route::get('/hatali', 'HataliController@index');
	Route::get('/kurye', 'KuryeController@index');
	Route::get('/bayi_giris', 'BayiGirisController@index');
	Route::get('/cari', 'CariController@index');
//	Route::get("/logo/{tarih}","LogoController@show");
	Route::get("order/create","OrderController@create");
	Route::get("urun","UrunController@index");
	Route::get("urun/list","UrunController@list");
	Route::get("toplar","TopController@index");
	Route::get("analiz","AnalizController@index");
});

Route::prefix('jobs')->group(function () {
	//Route::queueMonitor();
});
Route::group(['guard' => 'kurye'], function () {
	Route::get('/gonderi', 'GonderiController@index')->name("gonderi");
});
Route::group(['guard' => 'bayi'], function () {
	Route::get('bayi', 'BayiController@index')->name("bayi");
	Route::get('bayi/create', 'BayiController@create');
	Route::get("bayi/urun","BayiUrunController@index");
	Route::post('bayi/baski', 'UploadController@baski');
	Route::post("/bayi/baski/delete","UploadController@delete");
});

Route::group(["prefix"=>"api/v1"],function(){
	Route::put("gonderi/teslimet","GonderiController@teslimet");

	Route::get("irsaliye/{id}","IrsaliyeController@show_json");
	Route::put("irsaliye/save","IrsaliyeController@store_json");
	Route::put("irsaliye/op_save","IrsaliyeController@opstore_json");
	Route::put("irsaliye/op_new","IrsaliyeController@opnew_json");
	Route::put("irsaliye/op_sil","IrsaliyeController@opsil_json");
	Route::put("irsaliye/coupon_update","IrsaliyeController@coupon_update");

	Route::post("onay","OnayController@store");
	Route::put("onayla","OnayController@onaylandi");
	Route::put("sil","OnayController@sil_json");

	Route::post("hazirlik","HazirlikController@store");
	Route::put("hazirlandi","HazirlikController@hazirlandi");

	Route::post("uretimde","UretimdeController@store");
	Route::post("uretilen","UretilenController@store");
	Route::post("transferde","TransferdeController@store");
	Route::post("dagitimda","DagitimdaController@store");
	Route::post("cikista","CikislarController@store");
	Route::post("tum","TumController@store");
	Route::post("hatali","HataliController@store");
	Route::post("fatura","FaturaController@store");
	Route::post("search","TumController@search");

	Route::put("transfer","TransferdeController@transfer");
	Route::put("uretildi","UretimdeController@uretildi");
	Route::put("transfere","TransferdeController@transfere");
	Route::put("top_transfere","TransferdeController@top_transfere");
	Route::put("cikisa","DagitimdaController@cikisa");
	Route::put("dagitima","DagitimdaController@dagitima");
	Route::put("teslimet","DagitimdaController@teslimet");
	Route::put("iptalet","IrsaliyeController@iptalet");
	Route::put("cikmadi","IrsaliyeController@cikmadi");
	Route::put("hatali","IrsaliyeController@hatali");
	Route::put("uretimegeri","IrsaliyeController@uretimegeri");
	Route::put("basilanageri","IrsaliyeController@basilanageri");
	Route::put("top_degistir","IrsaliyeController@top_degistir");

	Route::post("takip","TakipController@store");
	Route::get("print/irsaliye/{id}","IrsaliyeController@printle");
    Route::post("print/mesaj","IrsaliyeController@mesaj_yaz");
    Route::post("print/barkod","IrsaliyeController@barkod_yaz");
    Route::post("print/etiket","IrsaliyeController@etiket_yaz");
    Route::get("print/barkod","IrsaliyeController@barkod_yaz");
    Route::post("print/cikis","IrsaliyeController@cikis_yaz");
    Route::get("print/fatura/{id}","FaturaController@print");
    Route::get("rawprint/fatura/{id}","FaturaController@rawprint");
    Route::get("xml/fatura/{id}","EfaturaController@store");

    Route::post("kurye","KuryeController@get");
    Route::put("kurye","KuryeController@store");
	Route::patch("kurye/{id}","KuryeController@update");

	Route::post("cari","CariController@get");
    Route::put("cari","CariController@store");
	Route::patch("cari/{id}","CariController@update");

	Route::post("urun","UrunController@get");
    Route::put("urun","UrunController@store");
    Route::post("urun/upload/{id}","UrunController@upload");
	Route::patch("urun/{id}","UrunController@update");
	Route::delete("urun/{id}","UrunController@delete");

	Route::post("top_urunleri","TransferdeController@urunler");
	Route::post("top_transfer","CikislarController@urunler");

	Route::post("top","TopController@get");
    Route::put("top","TopController@store");
    Route::post("top/upload/{id}","TopController@upload");
	Route::patch("top/{id}","TopController@update");
	Route::delete("top/{id}","TopController@delete");

	Route::post("bayi","BayiGirisController@get");
    Route::put("bayi","BayiGirisController@store");
	Route::patch("bayi/{id}","BayiGirisController@update");

    Route::post("gonderi","GonderiController@store");
    Route::get("irsaliye_item/{id}","GonderiController@irsaliye_item");

    Route::get("order/{id}","OrderController@show");
	Route::put("order","OrderController@store");
	Route::put("order/save","OrderController@update");
	Route::post("order/upload","OrderController@upload");

	Route::put("order/op_save","OrderController@opstore_json");
	Route::put("order/op_new","OrderController@opnew_json");
	Route::put("order/op_sil","OrderController@opsil_json");
	Route::put("order/coupon_update","OrderController@coupon_update");

	Route::get("products","ProductController@get");
	Route::get("subcustomer/{id}","CustomerController@subcustomer");

	Route::post("oku/barkod","IrsaliyeController@barkod_oku");
	Route::post("analiz","AnalizController@store");
});

Route::group(["prefix"=>"api/v1/bayi"],function(){
	Route::get("order/{id}","BayiController@show");
	Route::put("order","BayiController@store");
	Route::put("order/save","BayiController@update");
	Route::post("order/upload","BayiController@upload");
	Route::post("tum","BayiController@tum");
	Route::post("search","BayiController@search");
	Route::get("irsaliye/{id}","BayiController@show_json");
	Route::put("irsaliyeproduct/save","BayiController@op_save");
	Route::get("irsaliyeproduct/{id}","BayiController@op_json");
	Route::get("print/mesaj/{id}","BayiController@mesaj_yaz");
	Route::post("takip","TakipController@bayi");

	Route::post("urun","BayiUrunController@get");
    Route::put("urun","BayiUrunController@store");
	Route::post("urun/upload/{id}","BayiUrunController@upload");

	Route::patch("urun/{id}","BayiUrunController@update");
	Route::delete("urun/{id}","BayiUrunController@delete");
	Route::put("iptalet","BayiUrunController@iptalet");
	Route::post("print/cikis","BayiController@cikis_yaz");
});

Route::group(["prefix"=>"rapor"],function(){
//	Route::get("/","RaporController@index");
//    Route::post("/","RaporController@store");
//    Route::get("uruntoplam/{tarih1?}/{tarih2?}","RaporController@uruntoplam");
//    Route::get("uruntoplamFiyat/{tarih1?}/{tarih2?}","RaporController@uruntoplamFiyat");
//    Route::get("urunbazinda/{tarih1?}/{tarih2?}","RaporController@urunbazinda");
//    Route::get("urunkategori/{yil?}","RaporController@urunkategori");
//    Route::get("semturun/{tarih1?}/{tarih2?}","RaporController@semturun");
//    Route::get("kategori/{tarih1?}/{tarih2?}","RaporController@kategori");
//    Route::get("urunsatis/{tarih1?}/{tarih2?}/{sube_id?}","RaporController@urunsatis");
//    Route::get("sube_mutabakat/{tarih1?}/{tarih2?}/{sube_id?}","RaporController@sube_mutabakat");
//    Route::get("sube_urunler/{tarih1?}/{tarih2?}/{sube_id?}","RaporController@sube_urunler");
//    Route::get("orders/{sube_id?}/{ay?}","RaporController@orders");
//    Route::get("kuponlar/{tarih1}/{tarih2}","RaporController@kuponlar");
//    Route::get("excel/{tarih1}/{tarih2}/{sube_id?}","RaporController@excel");
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

class Order extends Model {

	use SoftDeletes;

    protected $guarded = array("id");

	public function orderproducts()
    {
        return $this->hasMany('App\Orderproduct','order_id');
    }

	public function irsaliyetras()
    {
        return $this->hasMany('App\Irsaliyetra','order_id');
    }

    public function getSiptarAttribute($value)
    {
        return $this->attributes['siptar'] = Carbon::parse($value)->format('d-m-Y');
    }

    public function setSiptarAttribute($value)
    {
        return $this->attributes['siptar'] = Carbon::parse($value)->format('Y-m-d');
    }

    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d.m.Y H:i');
    }

    public function getUpdatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d.m.Y H:i');
    }
}

app/Http/Controllers/PrintController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Product;
use App\Sube;
use Illuminate\Support\Facades\Auth;

class PrintController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {

    }

    public function etiket($product_id)
    {
    	$product = Product::find($product_id);
		$sube = Sube::find(1);

		$n = app("App\Repositories\Etiket\EtiketImage",[$product,$sube]);

		$img = $n->olustur();

		return $img->response();
    }


}

resources/views/print/barkod.blade.php
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
    <title>Barkodlar</title>
    <style>
        *,body,html{padding:0;margin:0;}

        @page
        {
            size: 210mm 297mm;/* this affects the margin in the printer settings */
            margin: 0 2mm 0 2mm;
        }

        body
        {
            /* this affects the margin on the content before sending to printer */
            margin: 0px;
        }

        img{
            padding:0;
        }
        @media print{
            .kart {display:none}
            .page-break  { page-break-before: always; }
        }

        .passcodeCell {
            width: 68mm;
            height: 37.4mm;
            /*border-style: dashed;*/
            align-content: center;
            position: relative;
        }
        .passcodeGrid {
            display: grid;
            grid-template-rows: repeat(8, 37.3mm);
            grid-template-columns: repeat(3, 68mm);
        }
        .right {
            position: absolute;
            right: 0;
            top: 0;
            bottom: 0;
            width: 38mm;
            font-size:12px;
        }
        .right img{
            padding-top:3mm;
            width:100%;
        }
        .right p{
            margin-left:2mm;
        }
        .left {
            position: absolute;
            left: 0;
            width: 25mm;
            top: 0;
            bottom: 0;

        }
        .left img{
            padding:3mm;
            display: block;
            max-width: 100%;
            max-height: 100%;
            width: 100%;
            height: auto;
        }
        .font-md{
            font-size:10px;
        }
        .font-xs{
            font-size:9px;
        }
    </style>
</head>
<body>
<?php $key=0;?>
<div class="passcodeGrid">
 @foreach($ops as $op)
 @for($adet=1;$adet<=$op->product_qty;$adet++)
  <div class="passcodeCell">
    <div class="left">
        <img src="{{$op->product_image}}" style="max-width:30mm;max-height:30mm;">
    </div>
    <div class="right">
        <img src="{!!\PicoPrime\BarcodeGen\BarcodeGen::generate([$op->irsaliye_no."-".$key, 40, 'horizontal', 'code128', 1])->encode('data-url')!!}" alt="barcode">
        <p>
            #{!!$op->irsaliye_no."-".$adet!!}<br>
            {{$op->product_width}}x{{$op->product_height}} <br>
            <span class="font-md">{{$op->product_name}} {{$op->mevcut_urun}}</span><br>
            @if($op->product_options)
            <span class="font-xs">{{$op->product_options}}</span><br>
            @endif
            <span class="font-md">{{$op->irsaliyesi->fatura_unvan}}</span>
        </p>
    </div>
  </div>
  @if($key%24==23 AND $key>0)
  </div><div class="passcodeGrid page-break">
  @endif
<?php $key++;?>
@endfor
@endforeach
</div>
</body>
</html>

resources/views/print/excel.blade.php
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Çıkışlar</title>
</head>
<body>
<?php $key=0;?>
<div class="Section1">

    <table>
        <tr>
            <th>Sipariş Tarihi</th>
            <th>İrsaliye No</th>
            <th>Kod</th>
            <th>Ölçü</th>
            <th>Adet</th>
            <th>Kalite</th>
            <th>Fatura</th>
        </tr>
    <?php $miktar = 0;$m2toplam=0;?>
    @foreach($ops as $op)
    <?php $miktar+= $op->product_qty;?>
        <tr>
            <td>
               {{date("d.m.Y",strtotime($op->irsaliyesi->siptar))}}<br>
            </td>
            <td>
                #{!!$op->irsaliye_no!!}
            </td>
            <td>
                {{$op->mevcut_urun}}
            </td>
            <td>
                <?php

                    if($op->stock){
                        $m2 = $op->product_qty * $op->stock->product_top * $op->stock->product_height / 10000;
                    }else{
                        $m2 = $op->product_qty * $op->product_top * $op->product_height / 10000;
                    }
                    $m2toplam +=$m2;
                ?>
                {{$op->product_width}}x{{$op->product_height}}  ({{$m2}})

            </td>
            <td align="center">
                {{$op->product_qty}}
            </td>
             <td>
                {{$op->product_name}}
            </td>
            <td>
                {{$op->irsaliyesi->fatura_unvan?:$op->irsaliyesi->gon_adsoyad}}
            </td>

        </tr>
    @endforeach
        <tr>
            <th colspan="3"></th>
            <th>{{$m2toplam}}</th>
            <th>{{$miktar}}</th>
            <th colspan="2"></th>
        </tr>
    </table>
</div>
</body>
</html>

resources/views/print/fatura.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Nefis Demet</title>
    <style type="text/css">


.clearfix:after {
  content: "";
  display: table;
  clear: both;
}

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
}
@page {
    size: A5 landscape;
    margin: 0 0 -40px 0;
}
@media print {
  html, body {
    width: 210mm;
    height: 148mm;
  }
}
html {
    /* off-white, so body edge is visible in browser */
    background: #eee;
}
table {
  border-collapse: collapse;
  border-spacing: 0;
}
.break{
  page-break-after: avoid;
}
body {
  position: absolute;
  width: 20.5cm;  
  height: 14.6cm; 
  margin:0 auto;
  color: #001028;
  font-family: 'Open Sans', sans-serif;
  font-size: 11px;

}
 @media print {
        html, body {
            border: 1px solid white;
            height: 99%;
            page-break-after: avoid;
            page-break-before: avoid;
        }
    }
    </style>
  </head>
  <body>
  
<div style="position:absolute;margin:4cm 12cm 8cm 1.5cm;font-size: 14px;">

  {!!$irsaliye->fatura_unvan ? $irsaliye->fatura_unvan : $irsaliye->gon_adsoyad!!}<br>

  {!!$irsaliye->fatura_adres ? $irsaliye->fatura_adres : $irsaliye->gon_adres!!}
    
</div>


<div style="position:absolute;margin:6.5cm 11cm 7.5cm 4.5cm;line-height: 1em;">

  {!!$irsaliye->vergi_dairesi ? $irsaliye->vergi_dairesi : "." !!}
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  {!!$irsaliye->vergi_no ? $irsaliye->vergi_no : $irsaliye->kimlik_no!!}
    
</div>

<div style="position:absolute;margin: 4cm 0 0 17cm;font-size: 11px;line-height: 1.6em;">
    {!!date("d.m.Y",strtotime($irsaliye->siptar))!!}<br>
    {!!date("d.m.Y",strtotime($irsaliye->siptar))!!}<br>
    {!!$irsaliye->irsaliye_no!!}<br>
    {!!$irsaliye->order_number!!}<br>
    {{--date("H:i",strtotime($irsaliye->updated_at))--}}
</div>
<?php $matrah8 = 0;$kdv8=0;?>
<?php $matrah18 = 0;$kdv18=0;?>
<div style="position: absolute;margin:8cm 1.5cm 4cm 1.5cm;line-height: 1em;font-size: 11px;">

   <table style="width: 17.5cm;">

      @foreach($irsaliye->orderproducts as $op)
      <tr>
        <td  class="service" width="2cm">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{!!$op->product_sku!!}</td>
        <td  class="service" width="8cm">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{!!$op->product_name!!}</td>
        <td class="unit" width="1.5cm">AD</td>
        <td width="3cm" align="center">{!! 1*$op->product_qty !!}</td>
        <td width="3cm" align="right">{!! number_format($op->product_price,2)!!}</td>
      </tr>
      <?php
      $discount = $op->ek == 1 ? 1 :  (100-$irsaliye->discount_yuzde)/100;
      $kdv8+= ($op->product_tax==8) ? 0.08 * $op->product_price*$op->product_qty * $discount : 0;
      $kdv18+= ($op->product_tax==18) ? 0.18 * $op->product_price*$op->product_qty * $discount : 0;
      $matrah8 += ($op->product_tax==8) ? $op->product_price*$op->product_qty * $discount : 0;
      $matrah18 += ($op->product_tax==18) ? $op->product_price*$op->product_qty * $discount : 0;
      $matrah18 += $irsaliye->shipping / 1.18;
      ?>
      @endforeach
     
  </table>
  
</div>

<div style="position: absolute;margin:9.5cm 11cm 5cm 1.5cm;line-height: 1.4em;font-size: 11px;">
  Matrah(%8) {{number_format($matrah8,2)}}<br>
  Matrah(%18) {{number_format($matrah18,2)}}<br><br>
 
</div>
<div style="position: absolute;margin:11.5cm 11cm 2cm 1.5cm;line-height: 1.4em;font-size: 11px;">
  {{money_tr_string($irsaliye->total+$irsaliye->shipping)}}
</div>
<div style="position: absolute;margin:11cm 1.5cm 1.5cm 16cm;line-height: 1em;font-size: 10px;">
  <table style="width: 3cm;line-height: 1em;font-size: 10px;">
    <tr>
      <td width="50%">&nbsp;</td>
      <td width="50%">&nbsp;</td>
    </tr>
    @if($irsaliye->coupon_discount>0)
    <tr>
      <td align="right">İndirim</td>
      <td align="right">-{{number_format($irsaliye->coupon_discount,2)}}</td>
    </tr>
    @endif
    <tr>
      <td align="right">Ara Toplam</td>
      <td align="right">{{number_format($irsaliye->subtotal,2)}}</td>
    </tr>
    <tr>
      <td align="right">Teslimat</td>
      <td align="right">{{number_format($irsaliye->shipping/1.18,2)}}</td>
    </tr>
    <tr>
      <td align="right">KDV (%8)</td>
      <td align="right">{{number_format($kdv8,2)}}</td>
    </tr>
    <tr>
      <td align="right">KDV (%18)</td>
      <td align="right">{{number_format($kdv18+($irsaliye->shipping-$irsaliye->shipping/1.18),2)}}</td>
    </tr>
    <tr>
      <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
      <td></td>
      <td align="right"><strong>{{number_format($irsaliye->total+$irsaliye->shipping,2)}}</strong></td>
    </tr>
  </table>
  
</div>
  </body>
</html>

resources/views/print/fatura2.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Nefis Demet</title>
    <style type="text/css">


.clearfix:after {
  content: "";
  display: table;
  clear: both;
}

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
}
@page {
    size: A5;
    margin: 0;
}
html {
    /* off-white, so body edge is visible in browser */
    background: #eee;
}
table {
  border-collapse: collapse;
  border-spacing: 0;
}

body {
  position: relative;
  width: 14.8cm;  
  height: 21cm; 
  margin:0 auto;
  color: #001028;
  
  
 background: url("/images/fatura.png") no-repeat top left;
  -webkit-background-size: contain;
  -moz-background-size: contain;
  -o-background-size: contain;
  background-size: contain;

  font-family: 'Open Sans', sans-serif;
  font-size: 10px;
}
    </style>
  </head>
  <body>
  
<div style="position:absolute;margin:175px 340px 10px 30px;">

  {!!$irsaliye->fatura_unvan ? $irsaliye->fatura_unvan : $irsaliye->gon_adsoyad!!}<br>

  {!!$irsaliye->fatura_adres ? $irsaliye->fatura_adres : $irsaliye->gon_adres!!}
    
</div>


<div style="position:absolute;margin:280px 10px 10px 120px;line-height: 1em;">

  {!!$irsaliye->vergi_dairesi ? $irsaliye->vergi_dairesi : "." !!}<br>

  {!!$irsaliye->vergi_no ? $irsaliye->vergi_no : $irsaliye->kimlik_no!!}
    
</div>

<div style="position:absolute;margin: 193px 0 0 445px;font-size: 10px;line-height: 1.8em;">
    {!!date("d.m.Y",strtotime($irsaliye->siptar))!!}<br>
    {!!date("d.m.Y",strtotime($irsaliye->siptar))!!}<br>
    {!!$irsaliye->irsaliye_no!!}<br>
    {!!$irsaliye->order_number!!}<br>
    {{--date("H:i",strtotime($irsaliye->updated_at))--}}
</div>
<?php $matrah8 = 0;$kdv8=0;?>
<?php $matrah18 = 0;$kdv18=0;?>
<div style="position: absolute;margin:360px 20px 10px 10px;line-height: 1em;font-size: 11px;">

   <table style="width: 500px;">

      @foreach($irsaliye->orderproducts as $op)
      <tr>
        <td  class="service" width="10%" style="font-size: 10px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{!!$op->product_sku!!}</td>
        <td  class="service" width="40%" style="font-size: 10px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{!!$op->product_name!!}</td>
        <td class="unit" width="10%" style="font-size: 10px;">AD</td>
        <td width="25%" align="center" style="font-size: 10px;">{!! 1*$op->product_qty !!}</td>
        <td width="15%" align="right" style="font-size: 10px;">{!! number_format($op->product_price,2)!!}</td>
      </tr>
      <?php
      $kdv8+= ($op->product_tax==8) ? 0.08 * $op->product_price*$op->product_qty *(100-$irsaliye->discount_yuzde)/100 : 0;
      $kdv18+= ($op->product_tax==18) ? 0.18 * $op->product_price*$op->product_qty *(100-$irsaliye->discount_yuzde)/100 : 0;
      $matrah8 += ($op->product_tax==8) ? $op->product_price*$op->product_qty *(100-$irsaliye->discount_yuzde)/100 : 0;
      $matrah18 += ($op->product_tax==18) ? $op->product_price*$op->product_qty *(100-$irsaliye->discount_yuzde)/100 : 0;
      ?>
      @endforeach
     
  </table> 
</div>

<div style="position: absolute;margin:510px 40px 10px 30px;line-height: 1.3em;font-size: 12px;">
  <table style="width: 480px;">
    <tr>
      <td width="60%"></td>
      <td width="20%"></td>
      <td width="20%"></td>
    </tr>
    @if($irsaliye->coupon_discount>0)
    <tr>
      <td></td>
      <td style="font-size: 10px;">İndirim</td>
      <td align="right" style="font-size: 10px;">-{{number_format($irsaliye->coupon_discount,2)}}</td>
    </tr>
    @endif
    <tr>
      <td></td>
      <td style="font-size: 10px;">Ara Toplam</td>
      <td align="right" style="font-size: 10px;">{{number_format($irsaliye->subtotal,2)}}</td>
    </tr>
    <tr>
      <td></td>
      <td style="font-size: 10px;">Teslimat</td>
      <td align="right" style="font-size: 10px;">{{number_format($irsaliye->shipping-$irsaliye->shipping/1.18,2)}}</td>
    </tr>
    <tr>
      <td style="font-size: 10px;">Matrah(%8) {{number_format($matrah8,2)}}</td>
      <td style="font-size: 10px;">KDV (%8)</td>
      <td align="right" style="font-size: 10px;">{{number_format($kdv8,2)}}</td>
    </tr>
    <tr>
      <td style="font-size: 10px;">Matrah(%18) {{number_format($matrah18,2)}}</td>
      <td style="font-size: 10px;">KDV (%18)</td>
      <td align="right" style="font-size: 10px;">{{number_format($kdv18+$irsaliye->shipping/1.18,2)}}</td>
    </tr>
    <tr>
      <td></td>
      <td style="font-size: 10px;">Genel Toplam</td>
      <td align="right" style="font-size: 10px;"><strong>{{number_format($irsaliye->total+$irsaliye->shipping,2)}}</strong></td>
    </tr>
    <tr>
      <td colspan="3">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3" style="font-size: 10px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{money_tr_string($irsaliye->total+$irsaliye->shipping)}}</td>
    </tr>
  </table>
  
</div>

  </body>
</html>